# Generated by Django 3.2.6 on 2021-08-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_pages', models.SmallIntegerField()),
                ('specialities', models.ManyToManyField(to='courses.Speciality')),
                ('teachers', models.ManyToManyField(to='courses.Teacher')),
            ],
        ),
    ]
