# Generated by Django 3.2.6 on 2021-10-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.SmallIntegerField(),
        ),
    ]
